server:
  port: 8080

spring:
  datasource:
    username: root
    password: 198303
    url: jdbc:mysql://localhost:3306/czl315?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

  mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: ttjj.dao

  #showSql
  logging:
  level:
  com:
  example:
  mapper : debug
